### ISSUE TITLE
서적 오타 관련 글

### ISSUE THREAD

**Issue by kokily** [velopert/learning-react#1]
575페이지 하단 부

parseInt(lastPage, 10);     ->     parseInt(lastPage, 10))

로 정정되어야 하는 것 같습니다!

**Comment by PEKKA4** [comment]
73페이지 코드에 props로들어가건 react인데 3-8에 출력결과는 React로 나와요

**Comment by velopert** [comment]
해결 되었습니다 :) 다음 버전에 반영됩니다.
