### ISSUE TITLE
불필요한 코드

### ISSUE THREAD

**Issue by SH5H** [velopert/learning-react#10]
348 페이지
post.js 에서 

import { handleActions, createAction } from 'redux-action';

에서 createActions은 불필요하니 없에는 게 맞는 것 같습니다. 괜히 혼란스러울 것 같습니다

**Comment by velopert** [comment]
그 뒷 부분에 redux-pender 를 사용하게 될 때 createAction 을 사용하게되니 방치하겠습니다.
