### ISSUE TITLE
5장 ref부분 질문드립니다.

### ISSUE THREAD

**Issue by SoSupreme** [velopert/learning-react#102]
```javascript

import React, { Component } from 'react';
import ScrollBox from './ScrollBox';

class App extends Component {
  render() {
    return (
      <div>
        <ScrollBox ref = {(ref) => this.scrollBox = ref}/>
        <button onClick={() => this.scrollBox.scrollTopBottom()}>맨 밑으로</button>
      </div>
    );
  }
}

export default App;
```

이 코드 에서 
```javascript
<button onClick={() => this.scrollBox.scrollTopBottom()}>맨 밑으로</button>
```
이 부분을
```javascript
<button onClick={this.scrollBox.scrollTopBottom}>맨 밑으로</button>
```
라고 하면 this.scrollBox가 undefined이라고 오류가 나는데요. 왜 그런지 궁금합니다. 그리고 왜 화살표 함수로 하면 되는 지도 궁금합니다.

**Comment by rurusyu** [comment]
저도 저기서 막혔는데...  this.scrollBox 라고 쓰신부분에서 실질적으로 가져오는 부분이 ScrollBox로 알고있는데, 소문자로 작성하신 이유가 있나요?

**Comment by rurusyu** [comment]
class ScrollBox에서 

clientHeigth 이부분이 console.log찍어보니깐 undefined으로 뜨는데..

**Comment by Hyegyeong310** [comment]
올려주신 코드가 직접 테스트하고 있는 코드 맞나요??
저는 create-react-app으로 만드니까 App 컴포넌트가 funtion 형태로 되어있었는데
렌더링 될 때 ref값을 불러와야 된다고 하는 부분 보고 class 형태로 바꿨더니 책에 나와있는대로 잘 작동됩니다.

`class App extends Component {
  render() {
    return (
      <div>
        <ScrollBox ref={ref => (this.scrollBox = ref)} />
        <button onClick={() => this.scrollBox.scrollToBottom()}>
          맨 밑으로
        </button>
      </div>
    );
  }
}`

**Comment by SoSupreme** [comment]
답변 감사합니다.
제가 궁금한 부분은 왜 초기렌더링할때 scrollBox가 undefined라고 책에서 설명되어있는가 하는 부분입니다. ㅜ.ㅜ 
실제 웹 페이지에서 확인해도, scrollToBottom이 undefined라고 뜨고, 저도 이게 맞는 것 같거든요.  
자식 컴포넌트의 ref를 아직 모르니 undefined라고 뜨지 않나라고 생각해서요.. 오탈자일까요?

**Comment by estylehq** [comment]
렌더 전의 scrollBox의 상태를 표기하는 게 아닌가 싶습니다.

**Comment by kbsowo14** [comment]
onClick={this.scrollBox.scrollDown} 라고 생각할 수도 있겠지만
이렇게 작성한다면 처음 렌더링 때 ref를 아직 잡아내기 전 시점이므로, this.scrollBox값이 undefined으로 나타날 수 밖에 없습니다. 그래서 오류라고 나타나는 것이죠.

그러므로 화살표 함수 문법을 사용하여 아예 새로운 함수를 만들어서 그 내부에서 this.scrollBox.scrollDown() 을 넣어 줍니다.

즉, 버튼을 누를 때에 this.scrollBox.scrollDown 메서드가 실행 되도록 함수로 감싸주는 것이죠.

**Comment by JiannKim** [comment]
5.1.2 App 컴포넌트에서 예제 컴포넌트 렌더링(페이지 146)  부분에서 App.js 컴포는 함수형에서 클래스형으로 전환시키라는 글을 제대로 안보고 임포트만 해서 저도 렌더링 오류가 발생했는데요. 

@Hyegyeong310 님 말씀 처럼 App.js를 클래스형으로 전환하니 잘 해결 됩니다.

`import { Component } from 'react';
import './App.css';
import ScrollBox from './5장.ref:DOM에_이름달기/ScrollBox';

class App extends Component {
  render() {
    // 5.2.2.2 App 컴포에서 스크롤 박스 컴포 렌더링
    return (
      <div>
        <ScrollBox
          // 5.3.4 컴포넌트에 ref 달고 내부 메서드 사용
          ref={(ref) => (this.scrollBox = ref)}
        />
        <button onClick={() => this.scrollBox.scrollToBottom()}>
          맨 밑으로
        </button>
      </div>
    );
  }
}

export default App;
`
