### ISSUE TITLE
P.490 VSCode 의 generate-react-component 확장프로그램이 작동하지 않습니다.

### ISSUE THREAD

**Issue by hihihoo** [velopert/learning-react#107]
확장프로그램에 문제가 있는것 같네요..

**Comment by epictrave** [comment]
저도 안되네요

**Comment by epictrave** [comment]
문제 해결 방법 찾았습니다.
해당 확장프로그램 라이브러리 보니까 fs.appendFile에서 오류가 있더군요. 
먼저 설치 해당 확장 프로그램 설치하시고

Windows : %USERPROFILE%\.vscode\extensions 
Mac : ~/.vscode/extensions 또는 /Users/<user>/.vscode/extensions 
Linux : ~/.vscode/extensions
확장 프로그램 폴더에 들어갑니다.
거기서 여러 확장 프로그램 폴더가 있을 겁니다.
joshjg.generate-react-component-0.2.1 폴더를 찾아 들어가서 extension.js 파일을 오픈합니다.
generate 함수안에 
`fs.appendFile(newFilePath, replacePlaceholders( computeConditionals(data.toString(), enabledOptions), componentName));` 의 코드가 있을 겁니다.
이코드를 `fs.appendFile(newFilePath, replacePlaceholders( computeConditionals(data.toString(), enabledOptions), componentName), (error)=>{if(error) throw error});` 로 수정후 저장하시고 VS Code를 재실행해서 하면 작동합니다!

**Comment by leoh7** [comment]
@epictrave 와.. 감사합니다 ㅋㅋㅋㅋㅋ 하도 오래전에 포기하고 일일이 만들어서 썼었는데...ㅋㅋㅋㅋ ㅠㅠ

**Comment by epictrave** [comment]
@leoh7 다행이네요 ㅎㅎ 그럼 이 Issue는 닫아 주시면 될것 같아요!

**Comment by leoh7** [comment]
@epictrave 제가 이슈 열은게 아니라서... 'ㅁ' ㅎㅎㅎㅎ

**Comment by SoSupreme** [comment]
@epictrave 대단합니다. 감사합니다. 덕분에 해결했네요.   
직접 발견하신 건가요? 아니면 혹시 해결방법의 소스를 알 수 있을까요?    
감사합니다.

**Comment by epictrave** [comment]
@leoh7 제가 착각했네요 
@SoSupreme 다행이네요 ㅎㅎㅎ 직접 찾았습니다.
해당 폴더만 만들어지고 컴포넌트랑 컨테이너가 안만들어지고 있더라구요. 해당 코드 찾아서 고쳤습니다.
고치고 나서 해당 깃헙 레포에 해결법 알릴려고 가보니 다른 외국개발자들분들도 콜백 에러 이슈를 적어 두었더라구요. 그런데 해당 오픈소스 개발자분께서 더이상 관리를 안하셔서 이슈 반영 안하시더라구요.
