### ISSUE TITLE
Deploy 과정에서 설정 문제

### ISSUE THREAD

**Issue by donghwipark** [velopert/learning-react#108]
현재 S3로 react build 한 부분 업로드 했는데 proxy 서버를 제외하고 제 node.js url로 직접 api를 보내고 있습니다. 

도메인이 달라 node.js에서 cors를 사용했는데 post 읽어오고, login 까지만 적용되고 글 작성이나 수정은 되지가 않는데 혹시 글 작성, 수정시에 authorization 부분 해결 할 수 있는 방법 알 수 있을까요?

**Comment by velopert** [comment]
쿠키를 사용하고 계신가요?
withCredentials 부분을 확인해야 할 것 같아요.

https://stackoverflow.com/questions/43002444/make-axios-send-cookies-in-its-requests-automatically
