### ISSUE TITLE
5장 ref 부분 오류 문의드립니다!

### ISSUE THREAD

**Issue by dkun9039** [velopert/learning-react#109]
```javascript
import React, { Component } from "react";
import ScrollBox from "./ScrollBox";

class App extends Component {
  render() {
    return (
      <div>
        <ScrollBox ref={(ref) => this.scrollBox = ref} />
        <button onClick={() => this.scrollBox.scrollToBottom()}>
          맨 밑으로
        </button>
      </div>
    );
  }
}

export default App;
```
```javascript
import React, { Component } from 'react'

export default class ScrollBox extends Component {
    scrollToBottom = () => {
        const {scrollHeight, clientHeight} = this.box;
        this.box.scrollTop = scrollHeight - clientHeight;
    }
    render() {
        const style = {
            border:'1px solid black',
            height:'300px',
            width: '300px',
            overflow: 'auto',
            position: 'relative'
        };
        const innerStyle = {
            width: '100%',
            height: '650px',
            background: 'linear-gradient(white, black)'
        }
        return (
            <div
                style={style}
                ref={(ref)=>this.div=ref}>
                <div style={innerStyle}/>
            </div>
        );
    }
}

```

5장에 나오는 예제대로 작성하고 실행해보았는데 
다음과 같은 오류가 발생해서 문의드립니다. 

TypeError: Cannot read property 'scrollHeight' of undefined
ScrollBox.scrollToBottom
src/ScrollBox.js:4
  1 | import React, { Component } from 'react'
  2 | 
  3 | export default class ScrollBox extends Component {
> 4 |     scrollToBottom = () => {
  5 |         const {scrollHeight, clientHeight} = this.box;
  6 |         this.box.scrollTop = scrollHeight - clientHeight;
  7 |     }
View compiled

ScrollBox.js에서 scrollToBottom부분을 여러가지 모양으로 바꿔봐도 여전히 scrollHeight를 정의할 수 없다고 나오네요.. ㅠㅠ 
답변 기다릴게요!

**Comment by leoh7** [comment]
return (
            <div
                style={style}
                ref={(ref)=>this.div=ref}>
                <div style={innerStyle}/>
            </div>
        );
여기 this.div 가 아니라 this.box 아닌가 싶습니다!

**Comment by dkun9039** [comment]
감사합니다 :)
