### ISSUE TITLE
오탈자 문제

### ISSUE THREAD

**Issue by jungpaeng** [velopert/learning-react#11]
코드 문제는 아닙니다만, 출판사에서 맞춤법을 제대로 짚고 넘어가지 못한 것 같아 제보 드립니다.

---
32페이지 3번째 줄
요소 개수가 **몇 백 개**, **몇 천 개** 단위로 많다면

몇 백 개 -> 몇백 개
몇 천 개 -> 몇천 개

'몇'이 수를 나타내는 말 앞에 올 때는 뒷말과 붙어 하나의 관형사가 된 것으로 보고 붙여 씁니다.

---
34페이지 2번째 줄
다시 한 번 강조하면 리액트는 프레임워크가 아니라 라이브러리입니다.

다시 한 번 -> 다시한번

국립국어원 2015년 표준정보보완심의회에서 '다시 한번'은 상황에 따라 띄어쓰기에 혼선이 있어, 의미 구별 없이 무조건 붙여 쓰는 것으로 통일하였다고 합니다. 이를 따라 '다시 한번'의 '한번'은 붙여 씁니다.

**Comment by jungpaeng** [comment]
50 페이지 노트 中
구 버전 -> 구버전
'묵은'이나 '낡은'의 뜻을 더하는 '구-'는 접두사이므로 붙여 씁니다.

**Comment by velopert** [comment]
감사합니다 :-)
반영되었습니다.
