### ISSUE TITLE
14챕터 remove쪽 잘못되었습니다.

### ISSUE THREAD

**Issue by unilep** [velopert/learning-react#13]
todos의 immutable-list 인 state 에
insert action을 발생시키면 id가 1씩 증가되어 저장되지만

이것이 실제 state의 list index와 일치하기 않기 때문에
remove에 논리적 오류가 있는것 같습니다.

**Comment by Produck** [comment]
![image](https://user-images.githubusercontent.com/17894639/44021384-9d01e348-9f1f-11e8-8d47-eadc1e6d682f.png)

저는 src/modules/todos.js 파일에서 TOGGLE과 REMOVE 이렇게 수정했습니다.

**Comment by unilep** [comment]
@Produck 
그 방법도 있지만 findIndex를 통해 모든 원소를 순회하는 로직입니다.

애초에 state와 list의 index를 일치해주는 것이 바람직해보입니다.

**Comment by Produck** [comment]
id와 index를 일치시킬 방법은 없지 않나요?
리스트 중간의 항목을 삭제하면 해당 아이템 이후 index가 전부 -1 되버리니 매번 id를 갱신해 줄 수 있는 것도 아니라고 봅니다.

**Comment by unilep** [comment]
@Produck 
뭐 방법은 여러가지 있겠지만은
[https://github.com/unilep/Todo-list](url)
이건 제가 id자체를 없애고 수정한겁니다.

사실 여기선 todo에 id가의미가 없어서요.

**Comment by velopert** [comment]
음..!! 정말 심각한 오류네요
왜 이런 실수를 저질렀지 :0 부끄럽군요..

https://github.com/velopert/learning-react/commit/a3ada1e5f96aba0c3e069d732952f4dcd0a5d1ad

위 커밋에서 수정되었습니다 :)
