### ISSUE TITLE
게시 취소된 확장 프로그램(react-beautify) - 41p

### ISSUE THREAD

**Issue by greatfarmer** [velopert/learning-react#18]
![image](https://user-images.githubusercontent.com/19537652/44029261-9dece556-9f37-11e8-893d-f37a2ab5e4f8.png)

41p의 VS Code 확장 프로그램 중 5. react-beautify가 위의 그림과 같이 게시가 취소된 것 같습니다.
> https://marketplace.visualstudio.com/items?itemName=taichi.react-beautify

**Comment by jungpaeng** [comment]
+) 이 확장 프로그램을 대체할만한 확장 프로그램이 있다면 알고싶습니다.

**Comment by velopert** [comment]
요즘은 보통 이 대신에 Prettier 를 사용합니다.

**Comment by velopert** [comment]
https://velopert.com/3671
를 참고해보시고.. 해당 플러그인은 원래 이전에 편집할때 분명히 제거요청했는데 해당 변화가 누락되어있네요..!
