### ISSUE TITLE
Eslint config 관련

### ISSUE THREAD

**Issue by SH5H** [velopert/learning-react#20]
411페이지에  eslintrc.js 를 수정한뒤에  계속 진행하려니

계속 
Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style
라는 eslint쪽에서 문제가 있다고 하길래

eslintrc.js를 

```
module.exports = {
  extends: 'airbnb-base',
  rules: {
    'no-unused-vars': 1,
    'comma-dangle': 0,
    'eol-last': 0,
    'no-console': 0,
    'linebreak-style': ['error', 'windows']
  }
};
```
이렇게 수정해주었습니다. 아무래도 윈도우즈 계열에서만 뜨는 문제같습니다.

**Comment by SH5H** [comment]
아 VSCODE 오른쪽 하단에  LF로 진행할건지  CRLF로 진행할건지 설장할 수 있는 곳이 있네요
오른쪽 하단에
줄: , 열 :   공백:     UTF-8  CRLF JavaScript  Prettier: 

이렇게 되어있는 곳에 CRLF를 눌러 LF로 바꿔주니 ESLINT 관련 오류 없이 잘 진행이 되네요

**Comment by SH5H** [comment]
위의 포스트대로 변환하니 이렇게 변환한 페이지에서만 적용되고
전체적으로 적용하려니

vscode 설정에가서 

```"files.eol": "\n",```

추가로 적어줘야하네요

**Comment by velopert** [comment]
반영되었습니다. 나중에 참고 노트로 내용을 추가하겠습니다.
