### ISSUE TITLE
코드 오류: 14.4.2.2 todos 모듈 생성

### ISSUE THREAD

**Issue by devheedoo** [velopert/learning-react#213]
> 참고: Ridibooks에서 구입한 전자책으로 학습 중입니다.

오류 위치는 14.4.2.2에서 /src/modules/todos.js 파일의 TOGGLE/REMOVE 리듀서를 정의하는 부분입니다.

id 기준으로 디스패치하지만, TOGGLE/REMOVE 리듀서는 index 기준으로 todo를 찾아서 오류가 발생합니다. 오류가 발생하는 시나리오 중 하나는 다음과 같습니다:
- todo 추가 > 맨 뒤 todo 제거 > todo 추가 > 맨 뒤 todo 제거 또는 토글

리덕스 적용 전 코드를 일부 추가하여 오류를 해결한 코드를 첨부합니다. 주석처리된 코드가 현재 책에 적힌 코드입니다.

```javascript
// src/modules/todos.js
export default handleActions({
  [INSERT]: (state, action) => {
    // ... (중략)
  },
  [TOGGLE]: (state, action) => {
    // const { payload: index } = action;
    // return state.updateIn([index, 'done'], done => !done);
    const { payload: id } = action;
    const index = state.findIndex(todo => todo.get('id') === id);
    return state.updateIn([index, 'done'], done => !done);
  },
  [REMOVE]: (state, action) => {
    // const { payload: index } = action;
    // return state.delete(index);
    const { payload: id } = action;
    const index = state.findIndex(todo => todo.get('id') === id);
    return state.delete(index);
  }
}, initialState);
```

**Comment by devheedoo** [comment]
오류가 제대로 해결되지 않아 다시 확인 중입니다.

**Comment by devheedoo** [comment]
`const index = state.findIndex(todo => todo.id === id);` 에서 `todo.id`를 `todo.get('id')`로 수정했습니다.

**Comment by devheedoo** [comment]
이슈 다루는 부분이 미숙해서 죄송합니다. 혹시 저자 분께서 확인하시고 이슈를 close 해주시는게 맞는 과정인가 싶어서 다시 open 합니다.

**Comment by velopert** [comment]
개정판이 아니여서 해당 부분 반영하기 어려울 것 같습니다 ㅠㅠ
감사합니다.
