### ISSUE TITLE
개정판 500p 오타관련 제보

### ISSUE THREAD

**Issue by nsddevil** [velopert/learning-react#214]
export default connect(
  ({ sample, loading }) => ({
    post: sample.post,
    users: sample.users,
    loadingPost: loading.GET_POST, //오타
    loadingUsers: loading.GET_USERS //오타
  }),
  {
    getPost,
    getUsers
  }
)(SampleContainer);

export default connect(
  ({ sample, loading }) => ({
    post: sample.post,
    users: sample.users,
    loadingPost: loading['sample/GET_POST'], //수정
    loadingUsers: loading['sample/GET_USERS'] //수정
  }),
  {
    getPost,
    getUsers
  }
)(SampleContainer);

참고로 책에는 오타이지만 예제파일에는 정상적으로 나와있네요

**Comment by vlpt-playground** [comment]
감사합니다 :)
