### ISSUE TITLE
개정판 560P 오타제보

### ISSUE THREAD

**Issue by nsddevil** [velopert/learning-react#215]
const chunks = Object.keys(manifest.files)
  .filter(key => /chunk\.js$/.exec(key))
  .map(key => `<script src="${manifest[key]}"></script>`)
  .join("");

**manifest[key] 부분을 manifest.files[key] 로 고쳐야 할듯**

function createPage(root) {
  return `<!DOCTYPE html>
    <html lang="ko">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <link href="${manifest["main.css"]}" rel="stylesheet"/>
        <title>React App</title>
      </head>
      <body>
        <noscript>You need to enable JavaScript to run this app.</noscript>
        <div id="root">${root}</div>
        <script src="${manifest["runtime~main.js"]}"></script>
        ${chunks}
        <script src="${manifest["main.js"]}"></script>
      </body>
    </html>`;
}

**manifest["main.css"], manifest["runtime~main.js"], manifest["main.js"] 부분을**

**manifest.files["main.css"], manifest.files["runtime~main.js"], manifest.files["main.js"] 로고쳐야 할듯**

ps. 공부하시는분들 헤매지 마시고 화이팅~~

**Comment by vlpt-playground** [comment]
감사합니다 :)

**Comment by oinochoe** [comment]
감사합니다. 덕분에 잘 해결했습니다.
