### ISSUE TITLE
p816 TabBox에서 Button 사이즈 이상한점.

### ISSUE THREAD

**Issue by kimpeupeu** [velopert/learning-react#219]
Input 태그가 flex: 1로 되어있습니다. 이는 min-width 미만으로 줄어들지 않습니다.
따라서 기본 min-width 크기로 적용되면서 form 전체 크기인 256px를 초과하여 button이 짤리게 됩니다.

![image](https://user-images.githubusercontent.com/17894639/65041447-c039a780-d991-11e9-8bb7-b9a3419eed90.png)

해결법: input 태그의 min-width를 설정해주면 됩니다. 190px정도 이하로 세팅하면 됩니다.
(저는 그냥 100px로 세팅했습니다.)
![image](https://user-images.githubusercontent.com/17894639/65041468-caf43c80-d991-11e9-9cf3-cbf63dfdd77e.png)

**Comment by velopert** [comment]
감사합니다 :)
운영체제는 윈도우 사용하시나요?
인풋의 min-width가 환경별로 조금씩 다른것같습니다..
다음 중쇄떄 업데이트 하겠습니다~

**Comment by kimpeupeu** [comment]
넵~ 윈도우에서 작업했습니다.
환경별로 다를거라 생각 못 했었네요.
좋은 책, 글, 강의 늘 감사합니다
