### ISSUE TITLE
구버전 함수

### ISSUE THREAD

**Issue by SH5H** [velopert/learning-react#22]
현재 mongoose 5.2.9 이고요

473페이지에서 posts.ctrl.js -list  테스트 해보는데
DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

라는 문구가 뜨네요 
당장 중요한건 아니지만 그래도 혹시 모르니 이슈로 남겨요

**Comment by velopert** [comment]
감사합니다 :)
