### ISSUE TITLE
개정판 880p 오류제보

### ISSUE THREAD

**Issue by nsddevil** [velopert/learning-react#220]
<PostViewer
      post={post}
      loading={loading}
      error={error}
      actionButtons={<PostActionButtons onEdit={onEdit} onRemove={onRemove} />}
      **ownPost={user && user.id === post && post.id}**
    />

위부분이 ownPost={user && post && user._id === post.user._id} 로 바뀌어야 할것같습니다.
또 ownPost 를 props로 보냈으나 책에는 쓰고있는곳이 나와있지 않습니다.

그리하여 components/post/PostViewer.js 파일에서

const PostViewer = ({ post, error, loading, actionButtons, **ownPost** }) => {
  // 에러 발생 시
  if (error) {
    if (error.response && error.response.status === 404) {
      return <PostViewerBlock>존재하지 않는 포스트입니다.</PostViewerBlock>;
    }
    return <PostViewerBlock>오류 발생!</PostViewerBlock>;
  }

  // 로딩중이거나, 아직 포스트 데이터가 없을 시
  if (loading || !post) {
    return null;
  }

  const { title, body, user, publishedDate, tags } = post;
  return (
    <PostViewerBlock>
      <Helmet>
        <title>{title} - REACTERS</title>
      </Helmet>

      <PostHead>
        <h1>{title}</h1>
        <SubInfo
          username={user.username}
          publishedDate={publishedDate}
          hasMarginTop
        />
        <Tags tags={tags} />
      </PostHead>
      **{ownPost && actionButtons}**
      <PostContent dangerouslySetInnerHTML={{ __html: body }} />
    </PostViewerBlock>
  );
};

props 로 ownPost를 받고 {ownPost && actionButtons} 를 적용하니까
작동합니다 공부하시는분들 참고하세요!!

p.s 비록 오탈자가 있어서 좀 해맸지만 좋은책 써주신 김민준님께 감사하며 아무것도 모르는 아저씨에서 간단한 홈페이지를 만들수 있게되었습니다 감사합니다~~

**Comment by velopert** [comment]
감사합니다 !!
