### ISSUE TITLE
개정판 4장 오탈자 및 질문이 있습니다.

### ISSUE THREAD

**Issue by Sedies** [velopert/learning-react#221]
4장에 127페이지 맨 윗줄 설명에 _"SyntheticEvent 및 네이티브 이벤트와 달리.." 가아니고 "SyntheticEvent **는** 네이티브 이벤트와 달리.." 가_ 맞지 않을까요? 제가 설명을 읽는 내내 이해가 잘 가지 않았어요 ㅠㅠ 만약 이게 오탈자가 아니라면 문장에 주어가 없는건데 설명이 필요합니다.

**Comment by velopert** [comment]
혼란을 드려서 죄송합니다!
오탈자에 반영되었어요~

~는 이 맞습니다
