### ISSUE TITLE
P.130 ~ P 133 임의 메서드 만들기 및 Property initializer Syntax를 사용한 메서드 작성 코드 에러

### ISSUE THREAD

**Issue by h2de6n** [velopert/learning-react#222]
> index.js:1375 Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    in input (at EventPractice.js:25)
    in div (at EventPractice.js:23)
    in EventPractice (at App.js:5)
    in App (at src/index.js:7)

> index.js:1375 Warning: Expected `onChange` listener to be a function, instead got a value of `string` type.
    in input (at EventPractice.js:25)
    in div (at EventPractice.js:23)
    in EventPractice (at App.js:5)
    in App (at src/index.js:7)

이런 오류가 뜹니다. 그리고 input 태그에 입력을 하려고 입력을 하면 아무런 반응이 없습니다.

**Comment by velopert** [comment]
책 내용을 확인해보았으나, 문제를 확인하지 못했습니다.
입력하셨던 코드를 여기에 붙여넣어주시겠어요?
