### ISSUE TITLE
개정판 9장 p233, p243 오탈자 제보입니다.

### ISSUE THREAD

**Issue by becover** [velopert/learning-react#225]
9.2.3 node_modules에서 라이브러리 불러오기 내용으로 라이브러리 두가지를 설치하고(include-media, open-color)적용하는 SassComponent.scss 예제에
_3번째줄 background: $oc-gray-2;로 되어있는데_ 이건 기본 백그라운드 색이여서 그림 9-4처럼 나오려면 _**수정전 코드인 background:black이 맞습니다**_. 아니면 화면을 줄이던 키우던 회색이 나와요!
이부분은 확인후 추후 수정바랍니다~

**Comment by Sedies** [comment]
앗 그리고 9장 p243에 StyledComponent.js 내용에서도
const StyledComponent = () => {
 //내용
}

여기에 내용들이 return이 감싸지지 않아서 여러줄이라 에러납니다.
return()으로 싸줘야해여..저 이거땜에 또 한참을 뒤졌어요 벨퍼님ㅠㅠ!

**Comment by velopert** [comment]
9.2.3. 검정색 배경이 나타나게 하기 위하여 창크기를 줄여보세요.
pg.243 자세히 보시면 `() => (...)` 입니다

중괄호가 아닌 소괄호로 적어보시면 될거예요 :) 한번 pg.90 을 확인해주세요.
똑같이, 바로 리턴한다는 의미인데 JSX 를 () 를 감쌌을뿐이랍니다.
