### ISSUE TITLE
개정판 199페이지 useEffect

### ISSUE THREAD

**Issue by kcchae** [velopert/learning-react#228]
Info.js 에서 언마운트될 때만 뒷정리 함수를 호출하고 싶을 때, useEffect 함수의 두 번째 파라미터에 비어있는 배열을 넣었습니다.

`React Hook useEffect has a missing dependency: 'name'. Either include it or remove the dependency array  react-hooks/exhaustive-deps`

이런 메시지가 뜨는데, 뭐가 잘못된 걸까요?

**Comment by velopert** [comment]
감사합니다 :)
