### ISSUE TITLE
yarn 설치 실패

### ISSUE THREAD

**Issue by velopert** [velopert/learning-react#229]
--without-node 가 사라졌다고 함.

https://github.com/yarnpkg/website/issues/913

curl -o- -L https://yarnpkg.com/install.sh | bash

로 대체하도록 해야겠다.

**Comment by SoSupreme** [comment]
brew를 이용하지 말고 바로 터미널에서 
```
curl -o- -L https://yarnpkg.com/install.sh | bash
```
명령어로 설치하라는 말씀이시죠?
