### ISSUE TITLE
092페이지 3. DOM 요소에만 이벤트를 설정할 수 있습니다. 에서요...

### ISSUE THREAD

**Issue by eonsang** [velopert/learning-react#23]
`javascript
<myComponent onClick={dosumething}/>
`

그냥 이름이 onClick인 props를 전달을 받는게 맞는건가요? ? ?
부모(app.js) 컴포넌트에서 자식컴포넌트(myComponent)로 props를 전달 하는게 아닌가요??

------------

초심자도 이해할수 있게 책 구성이 너무 좋은거같습니다! 감사합니다 👍

**Comment by velopert** [comment]
그런 의미로 작성했었는데.. 설명에 그 대상이 빠져있어서 오해의 여지가 있네요 :) 
설명 수정하겠습니다~
