### ISSUE TITLE
이슈라기 보다는.. 의견입니다. ㅠ

### ISSUE THREAD

**Issue by kbj0109** [velopert/learning-react#230]
안녕하세요. 집필하신 책 잘 보고 있습니다 ㅎㅎ

그런데 그냥 다른 책들과 비교했을 때 이런 점이 불편하지 않나 싶은 생각이 들어서요..

Git 에 올려주신 예제.
Chapter 를 소분화 하여 예제를 올려주시면 안될까요?

예를 들어 Chapter 15.1 / 15.2 ~ 15.7 이렇게 한 Chapter 내에서도 설명해주시는 내용이 많은데,
언제나 받을 수 있는건 마지막 Chapter 부분이다 보니 그 전 부분이 이해가 안가거나 문제가 생기면 이후 따라가기가 힘드네요.

물론 어떻게든 잘 보고 하면 해결은 되지만 저와 같은 불편을 겪는 분도 있지 않을까 하여 말씀 드립니다. ㅠㅠ  물론 제가 부족한 것도 알고 있습니다.

React를 알고 싶고, 이 책을 구입한 독자로서 더 흥하셨음 합니다 ㅎㅎ.

**Comment by velopert** [comment]
의견 반영하여 다음 서적에서 그렇게 진행해보도록 하겠습니다 ^^
