### ISSUE TITLE
개정판 오탈자 문의

### ISSUE THREAD

**Issue by cookatrice** [velopert/learning-react#231]
p.460 하단 리듀서의 REMOVE에서, 오탈자 발견했어요. 확인 바랍니다.

*오탈자 수정 전 :(
> ...
>       [REMOVE]: (state, action) => ({
>         ...state,
>         todos: state.todos.filter(todo => todo.id !== **action.id**),
>       }),
> ...

*오탈자 수정 후 :)
> ...
>       [REMOVE]: (state, action) => ({
>         ...state,
>         todos: state.todos.filter(todo => todo.id !== **action.payload**),
>       }),
> ...

**Comment by velopert** [comment]
감사합니다 ^^
