### ISSUE TITLE
서버 사이드 렌더링 오탈자 

### ISSUE THREAD

**Issue by imdigo** [velopert/learning-react#233]
560페이지 서버사이드 렌더링 예제 코드 중, JSON을 파싱하여 href 혹은 src로 넣어주는 부분에 오탈자가 있습니다.

`chunks`를 만드는 부분부터, `createPage` 함수까지
`manifest[key]`를 `manifest['files'][key]`로 수정하여야 정상 작동합니다. 
이렇게 하지 않으면 `manifest` 아래에서 `files` attribute를 참조하지 못하여 key를 넣어도 undefined를 반환받게 됩니다.

**Comment by imdigo** [comment]
깔끔하게 고치려면 더 깔끔하게 만들 수도 있을 것 같긴 한데, 일단
[고친 소스코드](https://github.com/imdigo/react-study/blob/ssr/src/index.server.js)
처럼 임시적으로 수정해보았습니다.

**Comment by velopert** [comment]
오탈자 정리 문서에 반영되어 있습니다.

https://github.com/velopert/learning-react/blob/master/corrections.md#2035-pg-560

오탈자로 인해 혼란을 드려 정말 죄송합니다!
이 오탈자는 2쇄에서 수정되었습니다 ;)

추가 문의사항 있으면 이슈 다시 열어주세요~
