### ISSUE TITLE
11.6 불변성의 중요성 이해가 안가는 부분이 있어서 질문 드립니다

### ISSUE THREAD

**Issue by irerin07** [velopert/learning-react#234]
불변성의 중요성 맨 처음 부분에서 다음과 같은 설명이 나오는데 잘 이해가 가질 않습니다.

리액트 컴포넌트에서 상태를 업데이트할 때 불변성을 지키는 것은 매우 중요합니다. 앞에서 useState를 사용해 만든 onToggle 함수를 다시 확인해 볼까요?

const onToggle = useCallback(id => {\
&nbsp;setTodos(todos =>\
&nbsp;&nbsp;todos.map(todo =>\
&nbsp;&nbsp;&nbsp;todo.id === id ? { ... todo, checked: !todo.checked } : todo,\
&nbsp;&nbsp;),\
&nbsp;);\
}, []);

----

위의 코드가 왜 useState를 사용해 만든 함수인가요?
제가 보기엔 useCallback을 사용해 만든 함수 같은데 잘 이해가 가질 않습니다..ㅜㅜ
혹시 내부에 있는 setTodos를 사용했기 때문에 useState를 사용했다고 설명해주신건가요?

**Comment by WOOGONG0204** [comment]
네 제 생각도 useState를 사용해서 setTodos 객체를 제공 받았기 때문에 useState라고 하신것 같습니다.

**Comment by velopert** [comment]
설명 개선했습니다. 감사합니다.
