### ISSUE TITLE
Joi 관련 질문

### ISSUE THREAD

**Issue by imdigo** [velopert/learning-react#236]
안녕하세요, 책 정말 잘 보고 있습니다.

개정 초판을 보고 있고, 22단원 mongoose를 실습하고 있습니다.
다름이 아니라, Joi documentation 에서 설치를 할 때 이제 @hapi/joi 로 설치를 하라고 되어 있고, 이에 따라 바뀐 documentation을 참고하니, v16부터는 validate()의 사용법이 바뀐 것 같네요.
이제 `Joi.validate()`가 아닌, `schema.validate()`의 형태로 사용해야 하는 것 같습니다.
[참고링크(Joi issue #2145)](https://github.com/hapijs/joi/issues/2145#issuecomment-549007564)

구버전 joi를 사용하는 경우 큰 문제 없이 실습이 가능하긴 한데, 실제 프로젝트에서는 어떤 방향으로 진행하는 것이 옳을까 궁금하기도 하고, `correction.md`에는 없는 내용이라 문의드립니다.

감사합니다.

**Comment by velopert** [comment]
`@hapi/joi`를 사용하고 `schema.validate` 를 사용하는것으로 수정하였습니다.
감사합니다~

**Comment by Eyes0n** [comment]
joi가Deprecated 되었다고 하셨는데 npm에서는 joi로 여전히 남아있고 공식홈페이지에서도 @hapi/joi가 아닌 joi로 require해서 쓴다고 예제에 나와있습니다. 다시 확인 부탁드립니다.
다만` joi.validate()`가 아닌, `schema.validate()`의 형태로 사용하라고 나와있습니다.
