### ISSUE TITLE
개정판 17.7.5 useActions유틸 Hook 질문

### ISSUE THREAD

**Issue by irerin07** [velopert/learning-react#240]
![image](https://user-images.githubusercontent.com/39554427/68950389-67ef1c80-07ff-11ea-959f-867dba12fac0.png)

```
import { bindActionCreators } from 'redux';
import { useDispatch } from 'react-redux';
import { useMemo } from 'react';

export default function useActions(actions, deps) {
  const dispatch = useDispatch();
  return useMemo(
    () => {
      if (Array.isArray(actions)) {
        return actions.map(a => bindActionCreators(a, dispatch));
      }
      return bindActionCreators(actions, dispatch);
    },
    deps ? [dispatch, ...deps] : deps,
  );
}
```

위의 코드를 사용하면 
Compiled with warnings.

./src/lib/useActions.js
  Line 14:5:  React Hook useMemo was passed a dependency list that is not an array literal. This means we can't statically verify whether you've passed the correct dependencies  react-hooks/exhaustive-deps
  Line 14:5:  React Hook useMemo has missing dependencies: 'actions' and 'dispatch'. Either include them or remove the dependency array                                           react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

이런 경고 메시지가 나오는데 왜 그런건가요?

`deps ? [dispatch, ...deps] : deps,`
이 부분을
`[actions, dispatch]`
로 변경해주면 경고 메시지는 사라지는데

올바른 방법인가요?

왜 저런식으로 코드를 짜셨는지 궁금하고 해결방법은 무엇인지 궁금합니다.

**Comment by velopert** [comment]
리덕스 문서에서 제공된 `useActions` 는 `deps` 를 추가 하고 싶은 경우를 대비하여 저렇게 `deps ? [dispatch, ...deps] : deps,` 라는 코드를 넣은 것 같네요.

그런데 생각해보면 `useActions` 에 `deps` 를 넣어야 하는 상황이 무엇이 있을지... 잘 모르겠네요!
따라서 작성하신것처럼 deps를 제거해도 무방할것같구요, 

또는 다음과 같이 eslint 규칙을 무시하도록 작성하셔도 

```
export default function useActions(actions, deps) {
  const dispatch = useDispatch();
  return useMemo(
    () => {
      if (Array.isArray(actions)) {
        return actions.map(a => bindActionCreators(a, dispatch));
      }
      return bindActionCreators(actions, dispatch);
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    deps ? [dispatch, ...deps] : deps
  );
}
```

참고로 책에서 useActions 를 다룬건 이런 방법이 있다.. 라는 것을 소개하기 위함이구요, 꼭 사용하실 필요는 없습니다. 저는 실무에서는 이렇게 안써요 ㅎㅎ

다음 개정판에서는 이 내용은 아마 없애지 않을까 싶어요, 불필요한 내용이라고 생각돼서요.

 감사합니다!
