### ISSUE TITLE
useRef 로컬 변수 사용법에 대한 질문

### ISSUE THREAD

**Issue by ad7549** [velopert/learning-react#241]
EBook 386p에 함수형 컴포넌트에서 로컬 변수를 사용할 때

const id = useRef(1);
const setId = n => {
&nbsp;&nbsp;id.current= n;
}
const printId = () => {
&nbsp;&nbsp;console.log(id.current);
}

이런 예시가 있는데

let id = 1;
const setId = n => {
&nbsp;&nbsp;id= n;
}
const printId = () => {
&nbsp;&nbsp;console.log(id);
}

이렇게 사용했을 때와 차이가 있나요? 왜 굳이 useRef를 사용해야 하는지 궁금해요.

**Comment by velopert** [comment]
컴포넌트에서 어떠한 변수를 선언하게 되면, 다음 렌더링을 할 때 해당 값이 유지되지 않고 모두 초기화됩니다.
때문에 useRef를 쓰는 것이구요 

만약 변수를 컴포넌트 바깥에서 선언한다면 괜찮긴 하겠지만 그렇게 하면 컴포넌트가 여러개가 되거나, 마운트/언마운트시 값이 초기화되지 않아 문제가 있기 때문에 직접 초기화하는작업을 하기도 해야겠지요
