### ISSUE TITLE
개정판 500페이지 오탈자 관련 문의

### ISSUE THREAD

**Issue by irerin07** [velopert/learning-react#242]
```
export default connect(
  ({ sample, loading }) => ({
    post: sample.post,
    users: sample.users,
    loadingPost: loading["sample/GET_POST"],
    loadingUsers: loading["sample/GET_USERS"]
  }),
  {
    getPost,
    getUsers
  }
)(SampleContainer);
```

위와 같이 코드를 수정을 했는데 

![image](https://user-images.githubusercontent.com/39554427/69322350-0825c500-0c88-11ea-96d1-4452b0007af8.png)

이런식으로 값이 읽혀들어오지 않습니다.

어느 부분을 잘못 한걸까요?

**Comment by wootae0204** [comment]
공부하던 학생입니다. 
코딩부분을 다 봐야 알것 같습니다. 제 생각으로는 API에서 값을 못받아 오는걸로 보이는데  위의 코드만으로는 확인이 불가능합니다.
