### ISSUE TITLE
개정판 p870번에 /@:username 처리가 잘못된것 같습니다

### ISSUE THREAD

**Issue by cokepizza** [velopert/learning-react#243]
책에서 location.search로부터 username을 받아오려고 하고 있는데,
username이 쿼리가 아닌 파라미터기 때문에 match.params로부터 username을 받아와야 정상작동합니다
수정 부탁드립니다

**Comment by cokepizza** [comment]
PostListContainer.js에서도 username 파라미터에 동일한 문제가 있습니다

**Comment by velopert** [comment]
감사합니다!
