### ISSUE TITLE
개정판 p.91 / p.105 / p.320 / p.359  검토 부탁드립니다. 

### ISSUE THREAD

**Issue by BrookeJung** [velopert/learning-react#245]
ch.3.2.3.1 p.91
위에서 선언한 MyComponent **클래스**를 

>   컴포넌트를

ch.3.4.1 p.105
이 함수가 호출되면 현재 클래스형 컴포넌트가 상속**하고** 있는 

>  받고있는

ch.12.1.5 p.320  두번째 예시코드
const update = **(draft** => {  

> produce(draft=>{

ch.14.1.3 p.359  async function run Task() 내부의 **increment** 함수들 전부

> increase

**Comment by velopert** [comment]
감사합니다 :)
