### ISSUE TITLE
20장 20.3

### ISSUE THREAD

**Issue by Neo0204** [velopert/learning-react#246]
webpack.config.server.js 파일 작성부분입니다.

서버부분을 빌드 하려 보니
options 부분의 exportOnlyLocals 부분이 그런 속성이 없다고 에러가 뜹니다.

- options has an unknown property 'exportOnlyLocals'. These properties are vali
d:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConventio
n?, onlyLocals? }

그래서 exportOnlyLocals의 키워드를 onlyLocals로 바꾸었는데 이번에 빌드는 되는데

ReferenceError: window is not defined
    at Module.<anonymous> (C:\Users\wootae\Desktop\react\20_ssr_recipe\dist\serv
er.js:1:1872)

레퍼런스 에러가 뜹니다. 

이부분 확인 부탁드립니다.

**Comment by talkdada** [comment]
저도 같은 증상인데
onlyLocals 로 바꾸고 빌드하고 서버띄우면
css적용안됩니다
버전업이되서그런가 
오류가 많은것 같습니다...

**Comment by WOOGONG0204** [comment]
네 저는 일단 서버 사이드 렌더링을 제외하고 개발하고 있습니다. 
문제를 해결하면 공유해 드리겠습니다.

**Comment by talkdada** [comment]
onlyLocals : true 로 변경후
manifest.files['main-css'] 이렇게 다바꿔보세요

**Comment by kdongha** [comment]
https://velog.io/@jihoson94/ReactJS-ServerSide-Rendering

**Comment by WOOGONG0204** [comment]
talkdada 님 
어디에있는 manifest를 고쳐야하는지 알려주실수 있나요?

**Comment by WOOGONG0204** [comment]
kdongha님 감사합니다만 블로그 대로 하니 다른에러가 뜹니다. 
SyntaxError : Unexpected end of input
    at Object.<anonymous> (C:\Users\wootae\Desktop\react\20_ssr_recipe\scripts\b
uild.server.js:12:16)
혹시 build.server.js:12:16의 12와 16의 의미를 알고 계신가요?

**Comment by talkdada** [comment]
> talkdada 님
> 어디에있는 manifest를 고쳐야하는지 알려주실수 있나요?

import React from "react";
import ReactDOMServer from "react-dom/server";
import express from "express";
import { StaticRouter } from "react-router-dom";
import fs from "fs";
import App from "./App";
import path from "path";
const manifest = JSON.parse(
  fs.readFileSync(path.resolve("./build/asset-manifest.json"), "utf8")
);
// const temp = `<script src="/static/js/2.9ace3854.chunk.js"></script>`;
const chunks = Object.keys(manifest.files)
  .filter(key => /chunk\.js$/.exec(key))
  .map(key => {
    console.log(key);
    return `<script src="${key}"></script>`;
  });

function createPage(root) {
  return `<!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8"/>
        <link rel="shortcut icon" herf="/favicon.ico"/>
        <meta
          name="viewpoint"
          content="width=device-width, inital-scale=1,shrink-to-fit=no"
         />
         <meta name="theme-color" content="#000000"/>
         <title>React App</title>
         <link href="${manifest.files["main.css"]}" rel="stylesheet"/>
         
      </head>
      <body>
        <noscript>You need to enable javascript to run this app.</noscript>
        <div id="root">
          ${root}
          
        </div>
        <script src="${manifest.files["runtime-main.js"]}"></script>
      
        ${chunks}
        <script src="${manifest.files["main.js"]}"></script>
       
      </body>
    </html>
  `;
}
const app = express();

const serverRender = (req, res, next) => {
  const context = {};
  const jsx = (
    <StaticRouter location={req.url} context={context}>
      <App />
    </StaticRouter>
  );
  const root = ReactDOMServer.renderToString(jsx);
  res.send(createPage(root));
};
const serve = express.static(path.resolve("./build"), {
  index: false
});
app.use(serve);
app.use(serverRender);

app.listen(5002, () => {
  console.log("Running on http://localhost:5002");
  // console.log(manifest);
  // console.log(manifest.files);
});


위에 코드 보시고 4개 manifest로 받는 것들 다 바꿔주세요

**Comment by kdongha** [comment]
> kdongha님 감사합니다만 블로그 대로 하니 다른에러가 뜹니다.
> SyntaxError : Unexpected end of input
> at Object. (C:\Users\wootae\Desktop\react\20_ssr_recipe\scripts\b
> uild.server.js:12:16)
> 혹시 build.server.js:12:16의 12와 16의 의미를 알고 계신가요?

12번째줄 16번째 글자로 알고있습니다.

**Comment by velopert** [comment]
늦게까지 해결을 못해드려 죄송합니다!!
시간 나는대로 솔루션 준비해드릴게요

즐거운 연휴되세요!

**Comment by WOOGONG0204** [comment]
도와주신 여러분들 덕분에 문제를 제시했던 부분을 해결했습니다. 
해결한 방법은 여러분들의 소스코드와  corrections.md를 참고하여 
해결하였습니다.

문제의 핵심이였던
git bash  yarn start:server 명령어 실행 시
ReferenceError: window is not defined at Module.  에러가 떳습니다.
에러가 발생한 시점은 정확히 555페이지인
index.server.js의 <div>Hello ssr!</div>를 렌더링 할 때라
manifest 작성 문제와는 관련이 없다고 생각합니다.

지금도 정확히 문제의 원인을 밝혀내진 못하였는데
webpack.config.server.js와 관련있지 않나 싶습니다. ( 아마 오타?...)
(안되서 webpack.config.server.js를 자꾸 수정하여보니 오류가 되었습니다.)
p.555에서 참고로
서버를 스타트 할 때
node dist/server.js 명령어와
yarn start:server 명령어를 사용하실시
서버는 동일하게 실행되나
전자는 gitbash의 화면에 console.log 반응하지만
node dist/server.js
<div data-reactroot="">Hello Server Side Rendering!</div>
후자는 gitbash부분에 반응이 없어도 서버는 열립니다.(저는 안되는줄알고 계속 start했네요)
yarn start:server
yarn run v1.19.1




도움을 주신 모든 분들께 감사드리며
신경 써주신 김민준 작가님께 감사드립니다.

즐거운 연휴, 연말 보내세요.

**Comment by velopert** [comment]
https://github.com/velopert/learning-react/blob/master/corrections.md#2032-pg-549-550-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8

기존 책의 예시는 위 변경사항만 적용하면 문제없이 작동합니다.

추가적으로, 섹션별로 진행 할 수 있도록 프로젝트도 분리했습니다.

https://github.com/velopert/learning-react/tree/master/20

감사합니다 :)
