### ISSUE TITLE
[질문] 일정 관리 웹 애플리케이션 만들기

### ISSUE THREAD

**Issue by minokuma** [velopert/learning-react#248]
수고하십니다.

질문 위치 : 10.3.2.3 todos 배열에 개 객체 추가하기

[App.js]

...

const onInsert = useCallback(

  text => {

    const todo = {

      id: nextId.current,

      text,       // <- 이 부분만 [key : value] 형태인 text: text, 가 아니라서 이해가 잘 안됩니다. ㅠㅠ

      checked: false,

    };

    setTodos(todos.concat(todo));

    nextId.current += 1;

  },

  [todos],

);

...

**Comment by velopert** [comment]
Property Shorthand라는 문법입니다.
해당 문법이 제대로 다뤄지지 않았네요.

다음 링크 참고해주세요.
https://alligator.io/js/object-property-shorthand-es6/
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Object_initializer


다음 개정판에서 해당 내용 추가하도록 고려하겠습니다.
감사합니다!
