### ISSUE TITLE
P.646  import/export 부분

### ISSUE THREAD

**Issue by Neo0204** [velopert/learning-react#250]
Node.js v12부터 ES Module 정식지원이라는 부분에서
저는  
type 키에 module이 아니라 export 값을 지정하고
 esm 설치, -r esm src/index.js , .eslintrc.json을 다 설정해 주어야 됩니다.
  
대신 main.js으로 변경하고  index.js부분은 사용하지 않았네요  사용해도 되고 , 안해도 되는 것으로 보입니다.

저와 같은 상황을 겪으신 분 있으신가요?

**Comment by velopert** [comment]
알고보니 v12 에서도 아직 정식지원이 아니였습니다..!
정식 지원은 조금 더 기다려야 할 듯 합니다 ㅎㅎ

해당 참고 노트는 제거하도록 하겠습니다.

감사합니다.
