### ISSUE TITLE
P. 771

### ISSUE THREAD

**Issue by Neo0204** [velopert/learning-react#251]
작업환경은 맥 OS입니다.
회원가입 API를 작성 후  console에 잘 찍히는 것을 확인 하기 위해 서버를 켰는데
현재 백엔드 서버는 꺼져있습니다. 동시에 2개를 실행하는 방법이 있나요? 
iTerm라는 터미널을 이용해 해결하였습니다. 다른 분들도 참고 하시면 좋을 것 같습니다.

**Comment by Neo0204** [comment]
이것보다 일반적인 방법이 있으시면 알려주세요!

**Comment by velopert** [comment]
이것을 물어보신건지는 잘 모르겠지만..!

![image](https://user-images.githubusercontent.com/17202261/74081605-2a173280-4a94-11ea-8523-80e1d38a8d02.png)

여기 + 버튼을 누르셔도 됩니다.

**Comment by Neo0204** [comment]
감사합니다 ! 덕분에 예제 프로젝트를 끝내고  AWS EC2 에 프로젝트를 옮기고 있습니다.
