### ISSUE TITLE
9장 컴포넌트 스타일링(Cannot find module 'babel-loader')

### ISSUE THREAD

**Issue by Holy-h** [velopert/learning-react#26]
$ yarn eject
후에
$ yarn start
를 입력 하면, Cannot find module 'babel-loader' 라는 오류가 발생합니다.
찾아보니 해당 링크(https://github.com/facebook/create-react-app/issues/4433)에서 해결책을 찾을 수 있었어요.
$ yarn start
전에
$ yarn add babel-loader
를 입력하면 오류가 없이 리액트 앱을 실행할 수 있더라고요.
처음 배우는 입장에서 해답을 쉽게 찾을 수 없을지도 모르겠다는 생각에 올려봅니다.

**Comment by kims3939** [comment]
현재 babel-loader 8.x 버전에서는 오류가 발생합니다. 예제 실행은 babel-loader 7.x로 설치하면 오류 없이 진행가능합니다.

**Comment by velopert** [comment]
가장 간단한 방법은 `yarn` 이라고 한번 입력하는건데요,
이 명령어를 입력하면 기존에 설치했던 모듈들을 예전에 설치했던 버전 그대로 재설치하게 됩니다.
