### ISSUE TITLE
개정판 p.336 오탈자 제보.

### ISSUE THREAD

**Issue by Kwakcena** [velopert/learning-react#267]
개정판 p.336을 보면

``` 
"이제 App 컴포넌트에서 Profile 컴포넌트를 위한 라우트를 정의해 보세요. 이번에 사용할 path 규칙에는 /profiles/:username 이라고 넣어 주면 됩니다." 
```

라고 되어있는데, 실제 실습 코드에서는 `/profile/:username` 으로 적용되어 있습니다.

복수형의 사용을 위해서 `profiles`로 적으시고 실습 코드는 `profile`을 적용하신 것 같습니다.

**Comment by velopert** [comment]
감사합니다 :)
