### ISSUE TITLE
[개정판] p864, 26장, update 태그 노출 오류

### ISSUE THREAD

**Issue by DavidYang2149** [velopert/learning-react#270]
안녕하세요.

서적을 통해 블로그를 완성 후 테스트를 진행하였는데 오류가 있어서 내용을 남깁니다.

**원본**
p864에서 src/api/posts/posts.ctrl.js - update 수정

```
export const update = async ctx => {
  (...)
  const nextData = { ...ctx.request.body }; // 객체를 복사하고
  // body 값이 주어졌으면 HTML 필터링
  if (nextData.body) {
    nextData.body = sanitizeHtml(nextData.body);**
  }
```

**오류 케이스**
블로그에서 새글 작성시 적용된 h1, h2, b 태그가 처음에는 정상적으로 작동하나 수정을 클릭하여 내용을 업데이트하면 해당 태그가 전부 사라지게 되었습니다.

하기에 하단과 같이 변경을 하였더니 정상적으로 작동 됩니다.
```
export const update = async ctx => {
  (...)
  const nextData = { ...ctx.request.body }; // 객체를 복사하고
  // body 값이 주어졌으면 HTML 필터링
  if (nextData.body) {
    nextData.body = sanitizeHtml(nextData.body, sanitizeOption);
  }
```

해당 내용이 수정되어야(sanitizeOption 추가) 할 것 같습니다.
확인 요청드립니다.

[추가] code-block의 경우 새글과 수정에서는 정상적으로 노출되나 해당 글을 뷰에서 보게 되면 정상적으로 표시가 되지 않는데 혹시 이 문제를 해결하신 분이 있으시다면 도움을 요청드립니다.
감사합니다.

**Comment by velopert** [comment]
감사합니다 :D

**Comment by velopert** [comment]
https://github.com/velopert/learning-react/commit/5906ea12e16b7f96708a1e5ee1c7aeb69de7f271 에서 수정되었습니다.
