### ISSUE TITLE
[개정판] p880, 27장, 오타있습니다.

### ISSUE THREAD

**Issue by leeyunhome** [velopert/learning-react#271]
안녕하세요?
책 잘 보고있습니다.
책 880페이지에 오류가 있습니다.

const ownPost = (user && user._id) === (post && post.user._id);

  return (
    <PostViewer
      post={post}
      loading={loading}
      error={error}
      actionButtons={
        ownPost && <PostActionButtons onEdit={onEdit} onRemove={onRemove} />
      }
    />
  );

이렇게 바꿔주셔야해요

감사합니다.

**Comment by velopert** [comment]
https://github.com/velopert/learning-react/blob/master/_old_corrections/%EA%B0%9C%EC%A0%95%ED%8C%90-1%EC%87%84.md#2712-pg-880
