### ISSUE TITLE
[개정판] 11장 setState() 함수형 업데이트 질문

### ISSUE THREAD

**Issue by DoParkEQ** [velopert/learning-react#272]
11장 11.5.1 의 예제에서 `setState()` 함수형 업데이트를 할 시에 `useCallback()`의 두번째 파라미터에 `useState()` 초기 값을 넣지 않아도 되는 이유가 뭔가요?
<img width="370" alt="Screen Shot 2020-04-24 at 11 25 53 PM" src="https://user-images.githubusercontent.com/59836949/80270054-f30ff080-8682-11ea-8911-922b5b85f375.png">

**Comment by velopert** [comment]
`setNumber` 함수 안에 업데이트 할 새로운 값이 아닌 업데이트 함수를 넣게 되면
상단에 선언되어있는 `number`값을 조회하는 것이 아니라 업데이트를 하는 과정에서 자체적으로 현재 값을 조회하기 때문에 `deps` 배열을 비워도 되는 것 입니다.
