### ISSUE TITLE
[개정판] p642 MongoDB 설치시 bin폴더가 보이지 않는 증상

### ISSUE THREAD

**Issue by SehoonKim630** [velopert/learning-react#273]
윈도우x64 환경에서 인스톨러를 내려받아 설치할 경우 Complete로 설치하면 bin폴더가 생기지 않습니다.

Custom으로 설치하면 bin폴더가 생기면서 책에서 나온대로 mongo 명령어로 설치여부 확인이 가능합니다.

확인부탁드립니다.

감사합니다.

**Comment by velopert** [comment]
6월 23일 기준 4.2.8 버전으로 설치했을 때 bin 디렉터리가 잘 만들어지는 것 같습니다..!
이슈 닫을게요 :) 감사합니다.
