### ISSUE TITLE
25.3.3  질문..

### ISSUE THREAD

**Issue by KimSungKwon** [velopert/learning-react#277]
로그인하고 /write 페이지로 가서

포스트 등록 버튼을 누르면

MongoDB  Compass Center 에는 포스트가 등록되었다고 나오지만

개발자도구 redux 탭에는 WRITE_POST_FAILURE 가 나오고,  post에도 null 로 그대로입니다.. history.push 주소부분으로 이동하는 코드도 실행이 안되구요...

몽고DB에 등록되는데 왜 WRITE_POST_FAILURE 가 나올까요 ㅠㅠ

**Comment by velopert** [comment]
프로젝트를 github에 올려주시고 링크 달아주시면 조사해볼게요 :D

**Comment by KimSungKwon** [comment]
https://github.com/KimSungKwon/react-project
프로젝트 업로드 했습니다!

**Comment by KimSungKwon** [comment]
해결됐습니다... api의 client 요청부분에서 중괄호를 써서 그랬어요...ㅠㅠ

**Comment by velopert** [comment]
해결돼서 다행이네요 !!
