### ISSUE TITLE
17장 코드스플리팅 웹팩 설정 관련해서

### ISSUE THREAD

**Issue by Mrchanghao** [velopert/learning-react#28]
지금 17장 코드스플리팅 부분에서 eject 해서 webpack.config.dev.js 파일을 책에 있는대로 수정 했는데 렌더링이 안되고 아래 같은 오류가 뜨는데 어떤 문제가 있고 해결 방법은 없을까요?  

```
./src/index.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/lnl2048/react-book/velopert/react-router-tutorial/node_modules/babel-preset-react-app/index.js
    at Array.map (<anonymous>)
    at Generator.next (<anonymous>)
```

**Comment by jonggyun** [comment]
저도 그런데 혹시.. 해결하셨으면 알려주실수 있나요?

**Comment by velopert** [comment]
일요일 전에 검토해보고 알려드리겠습니다 :) 두분께서 동일한 증상을 겪고있는것으로 보아 버전변화에 따른 오류같아보이기도 하네요..!

**Comment by jonggyun** [comment]
@velopert 빠른 답변 감사합니다!

**Comment by SH5H** [comment]
yarn 문제인지... npm으로 설치하니까 되긴하네요...

**Comment by Mrchanghao** [comment]
@SH5H 님과 @greatfarmer 님 하신대로 해도 제 에러는 사라지지가 않네여..ㅠㅠ

**Comment by velopert** [comment]
```
$ yarn add babel-loader@7
```
fㅡㄹ

**Comment by Mrchanghao** [comment]
@velopert 
오잉? 저 버전의 바벨로더를 설치 하니 제대로 렌더링이 되네여? 원인이 그냥 버전 차이에 따른 오류인가여? 
일단, 정말 감사합니다!!! ㅎㅎ
