### ISSUE TITLE
199쪽 info.js 예제 

### ISSUE THREAD

**Issue by velbie** [velopert/learning-react#289]
초판 2쇄

199쪽 맨 마지막 줄 
"오직 언마운트 될때만 뒷정리 함수를 호출하고 싶다면 useEffect 함수의 두 번째 파라미터에 **비어 있는 배열**을 넣으면 됩니다."

근데 바로 밑에 info.js - useEffect 예제에서는 [] 배열안에 name이 들어가 있어요.

**Comment by velopert** [comment]
감사합니다.

이제 보니, useEffect 쪽 설명이 좀 부실한것같은데 추후엔 설명을 좀 더 추가해야겠어요~

**Comment by velopert** [comment]
199 예시 코드에서는 다음과 같이 cleanup 부분에 name이 들어가지 않는 것이 맞습니다.
```
useEffect(() => {
  console.log('effect');
  return () => {
    console.log('cleanup');
}, [])
```

그리고 컴포넌트가 사라질 때 생태값을 확인하려면 상태 값을 ref 에 담아두거나, https://github.com/streamich/react-use/blob/master/docs/useUnmount.md 같은 커스텀 Hook을 사용하시면 됩니다.

**Comment by velopert** [comment]
https://github.com/velopert/learning-react/blob/master/corrections.md#823-pg-199-%EA%B0%9C%EC%84%A0
