### ISSUE TITLE
질문] p 317 예시코드를 실행하는 방법을 부탁드립니다.

### ISSUE THREAD

**Issue by ismaniac** [velopert/learning-react#300]
제목처럼 p 317의 예시코드를 확인해 볼수 있는 방법을 부탁드립니다.
VSCode에서는 그대로 실행되지 않는것을 확인했습니다.

굳이 React코드를 붙이지 않고 예시코드만 실행해볼수 있는 방법이 없나요 ?

import ... 문장이 없은 ECMAscript의 경우는
VSCode의 code runner라는 Plugin을 이용해서 실행이 가능 한것을 확인했는데,
예시 코드의 경우는 그렇게 되지 않고 react component를 만들고 그곳 immer 관련 코드를 넣어서 테스트가 가능한거 같은데
그런 방법이 아닌 예시코드만 실행시켜서 확인 가능한 방법을 알수 있을까 해서 질문드립니다.

감사합니다.

**Comment by velopert** [comment]
```
console.log(nextState)
```

같은 형태로 결과를 출력하도록 하고, 해당 파일을 index.js 에서 불러오는 식으로 하셔도 되고,
CodeSandbox 같은곳을 사용하는것도 편합니다.

**Comment by velopert** [comment]
아니면
node 명령어를 실행하신 뒤


```
const produce = require('immer'):
```


하시고 나서 스크립트를 작성해나가시면 됩니다.
