### ISSUE TITLE
Joi.validate 문법이 변경된듯 합니다.

### ISSUE THREAD

**Issue by sundoforce** [velopert/learning-react#302]
https://github.com/velopert/learning-react/blob/144f3d7f2c0912c1b3f1dd667dd8e71b947b6179/23/blog/blog-backend/src/api/auth/auth.ctrl.js#L21

const result = Joi.validate(ctx.request.body, schema);
에서 
const validation = schema.validate(ctx.request.body);
으로요

// const result = Joi.validate(ctx.request.body, schema);
  const validation = schema.validate(ctx.request.body);
//  if (result.error) {
if (validation.error) {
  ctx.status = 400;
    ctx.body = result.error;
    return;
  }

이상 슈퍼초보 개발자가 올립니다.
리엑트를 다루는 기술 책 감사합니다.

**Comment by velopert** [comment]
책은 업데이트 했는데 제가 기존 코드 업데이트를 안했네요! 업데이트 했습니다. 감사합니다.
