### ISSUE TITLE
p 560 index.server.js 오타 수정 요청(2쇄)

### ISSUE THREAD

**Issue by dannyryu4758** [velopert/learning-react#304]
function createPage(root, stateScript) {
(...)
 <script src="${manifest.files['runtime~main.js']}"></script>
(...)
};

"~" 을 "-" 로 수정

**Comment by passedball** [comment]
혹시 570 페이지 PreloadContext 예제 실행하는 데 문제 없으셨나요?
[https://github.com/velopert/learning-react/issues/308](url)

**Comment by velopert** [comment]
감사합니다. 수정됐습니다.
연관 이슈: #314
