### ISSUE TITLE
ESLint 설정 yarn 에러 409p

### ISSUE THREAD

**Issue by greatfarmer** [velopert/learning-react#31]
$ yarn global add eslint 실행시 아래 에러 발생
```
error eslint@5.4.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
```
아래는 저의 node, npm, yarn 버전 정보입니다.
```
node -v
v8.9.4

npm -v
5.8.0

yarn -v
1.9.4
```

위의 yarn에러를 해결하지 못해서 아래와 같이 npm으로 진행한 상황입니다.
(npm으로 패키지 설치시 에러가 발생하지 않았습니다.)
$ npm install -g eslint
$ npm add eslint
$ eslint --init

시간이 되신다면, 이 부분 확인해주시면 감사하겠습니다.

**Comment by greatfarmer** [comment]
생각해보니, 책에 나와 있는 것처럼 ESLint가 진도를 진행하는데 필수적인 사항이 아니기 때문에
package.json에서 ESLint 부분을 삭제한 이후 다른 패키지들을 yarn으로 설치해서 진행하고 있습니다.

짧은 소견으로는 ESLint와 yarn 간에 어떤 문제가 있지 않을까 싶습니다.

**Comment by velopert** [comment]
Node 버전을 최신버전으로 설치하시면 해결 될 것 같아요!

"^6.14.0 || ^8.10.0 || >=9.10.0"

의미는 6.14.x, 8.10.x, 9.10 이상버전에서 사용 가능하다는건데,
한번 node 를 최신 LTS 로 설치하시면 해결 될 듯합니다.

**Comment by greatfarmer** [comment]
코멘트 해주신 것과 같이 node버전을 최신버전인 v8.11.4로 업그레이드 이후 문제가 해결되었습니다.
감사합니다.

그리고, 이 문제로 인해 중간 중간 npm을 사용한 패키지가 있는데, 문제가 없을까요?
다시 말해, 패키지 추가에 npm과 yarn을 혼용해서 사용해도 괜찮은 건지요?
