### ISSUE TITLE
27-1 수정 파트 쪽 오류가 있어서 그런데 알려주세요..

### ISSUE THREAD

**Issue by wonlee6** [velopert/learning-react#310]
![image](https://user-images.githubusercontent.com/21251988/103151441-845ed600-47c1-11eb-836b-da86a0726235.png)

body 부분의 내용이 들어가는 거 까지는 잘 되는데 수정 할시 

body 부분이 [object Object] 로 바뀌어서 나오는데 짐작 가는 부분 있을까요 ?? 
다른 title, tag는 잘 변경되어 나옵니다. ㅠㅠ

**Comment by wonlee6** [comment]
오류 찾았습니다 ... 
^17.3.0 버전으로 하면 오류 생기네요 
깃에 올려져 있는 14.3.1로 바꾸니 오류 사라졌습니다.

**Comment by velopert** [comment]
```diff
- Joi.validate(ctx.request.body, schema);
+ schema.validate(ctx.request.body); 
```

이렇게 바뀌었으니 참고하세요~

**Comment by velopert** [comment]
참고: https://github.com/velopert/learning-react/blob/master/_old_corrections/%EA%B0%9C%EC%A0%95%ED%8C%90-2%EC%87%84.md#2292-pg669---672-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8
