### ISSUE TITLE
206페이지 useMemo 관련 질문입니다. 

### ISSUE THREAD

**Issue by zerocy18** [velopert/learning-react#312]
206쪽에 첫 문단에 getAverage함수가 계속 호출되는것은 확인했는데
이것의 정확한 이유가 어떻게 될까요?
상태값인 number가 바뀌면서 그 값을 파라미터로 받는 건가 했는데
파라미터는 list 여서 아닌거 같아서 
이렇게 질문 드립니다 ㅜㅜ

**Comment by velopert** [comment]
컴포넌트는 number 값이 변경될때마다 리렌더링이 됩니다. 
useMemo를 사용하기전에는 리렌더링이 될 때마다 getAverage 함수가 호출되고 있는 것입니다.
useMemo를 사용하면, list 배열이 바뀔때만 해당 함수가 호출됩니다.
