### ISSUE TITLE
3.4.1.3 Counter.js - Button setState prevState

### ISSUE THREAD

**Issue by lustertimber** [velopert/learning-react#315]
아래와 같이 처리하였지만 숫자의 증가가 +2가 되지 않습니다.
현기증이 납니다. 답변 부탁드립니다~

import React, { Component } from 'react';

class Counter extends Component {
	state = {
		number: 0,
		fixednumber: 0,
	};
	render() {
		const { number, fixednumber } = this.state;
		return (
			<>
				<h1>{number}</h1>
				<button
					onClick={() => {
						this.setState((prevState) => {
							console.log(prevState, prevState.number, number);
							return {
								number: prevState.number + 1,
							};
						});
					}}
				>
					+1 Button
				</button>
			</>
		);
	}
}
export default Counter;

**Comment by velopert** [comment]
코드가 두 페이지에 있어서 헷갈리신것같아요! 해당 함수에선 this.setState를 두번 호출하고 있어요.
참고 코드: https://codesandbox.io/s/cocky-rhodes-yjb71?file=/src/App.js
