### ISSUE TITLE
안녕하세요. 코드가 잘못 반영된거 같아 문의 남깁니다.

### ISSUE THREAD

**Issue by rae-han** [velopert/learning-react#321]
ebook으로 보고 있는데 30.3.2 맨 마지막에 환경변수 주입하는 코드가 잘못된거 같습니다. 마침 많이 배워서 책도 샀었는데 책에는 코드가 제대로 돼 있더라고요. 확인 부탁드립니다.(책에서는 p552~p553 넘어가는 내용 이었습니다.)

추가로 ebook에는 개정된 내용이 반영이 안될까요? 아니면 특정 트리거가 발생해야 반영이 되는 구조인가요?

**Comment by rae-han** [comment]
추가로 ebook에는 개정된 내용이 반영이 안될까요? 아니면 특정 트리거가 발생해야 반영이 되는 구조인가요?

**Comment by velopert** [comment]
늦게 답변드려 죄송합니다!
이 부분은 [길벗 출판사](https://www.gilbut.co.kr/) 1:1 문의를 부탁드립니다.
