### ISSUE TITLE
mongoose.connect 일부 옵션 deprecated 이슈

### ISSUE THREAD

**Issue by epark-grace** [velopert/learning-react#329]
안녕하세요 벨로퍼트님

22.3.2 예제에 사용된 useNewUrlParser, useFindAndModify 옵션은 더 이상 지원되지 않아 에러가 발생합니다.
mongoose 6버전 이후로는 해당 옵션이 각각 true와 false로 이미 설정된 것처럼 작동한다고 합니다.
reference: [No More Deprecation Warning Options](https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options)

**Comment by velopert** [comment]
알려주셔서 감사합니다. 
다음 인쇄때 반영하겠습니다.
