### ISSUE TITLE
22장 645 페이지 mongoose 연결 부분 useFindAndModify 삭제해야되요 !!!

### ISSUE THREAD

**Issue by wogus216** [velopert/learning-react#359]
MongoParseError: option usefindandmodify is not supported
만약 이 에러가 나오시면 useFindAndModify 삭제하면 정상작동 합니다.
mongoose 6버전 이상에서 더이상 지원안한다고 하네요 물론 4 대 버전 사용하면 문제없을 건 같긴해요.

**Comment by velopert** [comment]
#329
