### ISSUE TITLE
node_modules 오류?

### ISSUE THREAD

**Issue by Jmoon04** [velopert/learning-react#377]
node_modules파일에서 오류가 난건지 node_modules\mongodb\lib\collection.js:71 다음경로에서 에러가 납니다.
SyntaxError: Invalid or unexpected token라고 뜨네요...

**Comment by seuyan13** [comment]
저도 같은 곳에서 에러가 나와 해결 방법 알고싶어 코멘트 남깁니다.
22.4장에서 src/index.js 파일 이름을 main.js로 바꾼후에 에러가 뜹니다.

**Comment by velopert** [comment]
#381 확인해주세요! 감사합니다.
