### ISSUE TITLE
[개정판] 데이터 베이스 연결 에러

### ISSUE THREAD

**Issue by seuyan13** [velopert/learning-react#378]
22.4장에서 main.js 파일을 index.js 파일로 바꾼후에

blog-backend/node_modules/mongodb/lib/collection.js:70
            pkFactory: db.options?.pkFactory ?? utils_1.DEFAULT_PK_FACTORY,
이 에러가 뜨는데 어떻게 해결해야 하나요?

혹시나 싶어 22.4 마지막장의 코드까지 다 해봤는데도 해결이 안되고 아무리 구글링을 해봐도 해결을 못하겠습니다

**Comment by velopert** [comment]
#381 확인해주세요! 감사합니다.
