### ISSUE TITLE
17장. 코드 스플리팅

### ISSUE THREAD

**Issue by graffiti4u** [velopert/learning-react#39]
17장 진행중에 yarn eject 후 진행할려고 하면 babel/core 및 웹팩 오류가 나서 더 이상 진행을 하지 못합니다.

제가 직적만든 프로젝트에서는 
React & Plugin/Preset files are not allowed to export objects, only functions. 오류로 인해 예제 테스트가 되지 않아 저자님 소스를 가져다 테스트를 해 본 결과 오류없이 잘 만들어집니다.

제 프로젝트에서는 안된 이유가 무엇인지 알려주시기 바랍니다.

**Comment by velopert** [comment]
`yarn eject` 이후에 babel-loader 를 제대로 설치하지 못하는 이슈가 종종 발생하는데.. yarn 쪽 문제인것같아요.
이에 대한 해결법은,

```
yarn eject
yarn install
```

이런식으로 yarn install 명령어를 한번 더 입력해주시면됩니다. (혹은 yarn 이라고만 입력해도 됩니다)
