### ISSUE TITLE
react 프로젝트 생성시 책과 다른 디렉토리 구조 및 코드

### ISSUE THREAD

**Issue by Soorealbutnice** [velopert/learning-react#43]
안녕하세요. 리액트를 다루는 기술 책을 구입하여 현재 todo-list 만드는 부분을 공부하고 있습니다.

그런데 create-react-app todo-list를 하고 기본 webpack설정을 하려고 하는데

프로젝트를 만들자마자 본 webpack.config.dev.js파일의 코드와 책의 코드가 다르고

파일명 역시 registerServiceWorker.js 파일이 아닌 serviceWorker.js파일이 생깁니다.

아직 모르는 게 많아 기본 설정부분에서 조금 다른 부분이 생기니 대처를 제대로 못하는 거 같은데

이 부분은 어떻게 해야 할까요..

아! 제가 코드를 잘못 본 건 아닌가 해서 벨로퍼트님이 올려주신 예시 코드 중에서 config 폴더 안의 파일들을 그대로 가져와 사용해봐도 에러가 발생합니다ㅜ

**Comment by velopert** [comment]
https://github.com/velopert/learning-react#%EC%9D%BD%EC%96%B4%EC%A3%BC%EC%84%B8%EC%9A%94

이 부분을 참고해주세요 :)
이전버전으로 진행해도 배우는 것에는 지장없습니다.
다만 새 버전의  CRA  에선 무엇이 바뀌었는지 잘 알아두세요~
