### ISSUE TITLE
질문! p 548쪽

### ISSUE THREAD

**Issue by kohahn** [velopert/learning-react#45]
안녕하세요!

1. 548쪽에 handleChangeMarkdown을 호출하는 부분이 없는데 어디서 호출하는것이고

변수로 받아오는 doc은 어디서받아오는건가요 ?

2. 위지윅에디터를 써보려고하는데
이미지와 텍스트 내용이 있는데

이미지 와 텍스트 따로 업로드 하려는데 방법이 생각이 안나는데 어떻게 같이 수행하나요 ?

이미지업로드 multer쓸때 폼데이터를 써야되는데 위지익에디터에서는 어떻게해야되는지 잘모르겠습니다!

감사합니다..

**Comment by hwj0623** [comment]
1. EditorPane 컴포넌트 마운트 시에 호출하는 `initializeEditor`로 이벤트 리스너를 등록할때 핸들러 함수로 `handleChangeMarkdown` 호출합니다.  
- `EditorPane.js`에서 ` this.codeMirror.on('change', `this.handleChangeMarkdown);` 참고하시면 될듯합니다.

- `doc` 파라미터는 `marked` 모듈에서 해당 마크다운 입력창의 이벤트 파라미터 (일반 js에서 이벤트리스너 등록시 핸들러에 이벤트 객체인 `e` 를 자연스럽게 파라미터로 넘기는 것처럼)  같습니다.

2번은 잘 모르겠네요.
