### ISSUE TITLE
163p webpack.config.dev.js 설정관련 CRA v2로 eject 하셨다면..

### ISSUE THREAD

**Issue by Duckuism** [velopert/learning-react#51]
CRA v2로 eject하신 분들이 계시다면..!

이제는 기본적으로 CSS Module을 지원하네요.

따라서 컴포넌트 스타일링 시에 CSS module을 사용하기 위해 webpack.config.dev.js 옵션을 바꿀 필요가 없어졌고, 기본에 App.css대신 App.module.css로  확장자만 변경한 후 

```
import React, { Component } from 'react';
import styles from './App.module.css';

console.log(styles);

class App extends Component {
  render() {
    return (
      <div className={styles.box}>
      asd
      </div>
    );
  }
}

export default App; 
```

위와 같이 사용하면 되네요! 혹시 막히신 분들은 이거 보고 실습해보시길..^^;;

책 보면서도 너무 유익해서 계속 개선해서 더 좋은 책이 될 수 있었으면 하는 마음에 이슈 올립니다~! 벨로퍼트님 항상 감사드립니돠!

**Comment by djffk124** [comment]
10장 일정관리 웹 애플리케이션 생성..
과정 부분에서,,  위에 https://velog.io/@velopert/react-component-styling 위에 설정 대로 적용하고,,, 책에 있는 내용 그대로 코딩 해보았는데 ㅠ.ㅠ 자꾸 오류가 나요  도움 주시면 감사하겠습니다
