### ISSUE TITLE
7장 life cycle : getDerivedStateFromProps() 함수 호출시기

### ISSUE THREAD

**Issue by almond-bongbong** [velopert/learning-react#52]
![image](https://user-images.githubusercontent.com/42146674/46938936-f98dd700-d09f-11e8-97bc-24f2a4844391.png)
책 내용에 getDerivedStateFromProps 함수는 state가 변경될때는 호출이 안되는것으로 이해를 하였는데 예제의 더하기 버튼을 클릭 (setState) 했을때도 getDerivedStateFromProps 함수가 호출되는 것으로 보입니다. 아마도 최근 예제를 받아 모듈을 설치했을시에 react 16.4 v 이상으로 설치 되면서 이부분이 변경된것으로 보입니다.
https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops
http://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/

**Comment by YongHoonJJo** [comment]
저도 이부분이 애매했었는데, 감사합니다!!
