### ISSUE TITLE
p195 open-color 적용

### ISSUE THREAD

**Issue by weaklion** [velopert/learning-react#54]
open-color 적용이 안되네요.
최신 버전이라 안되는 줄 알고 scrpt도 1.1.5 버전으로 바꾸고 
confgi의 webpack.config.dev.js랑 path.js를 바꿔도 적용이 안됩니다.
Failed to compile.

./src/styles/main.scss
Module build failed:
    background: $oc-gray-1;
               ^
      Undefined variable: "$oc-gray-1".
      in C:\project\todo-list\src\styles\main.scss (line 4, column 17)
이런 오류가 뜨면서 안되네요 .
utils에 @import '~open-color/open-color' 하니 밑줄 뜨면서
Unable to open '_utils.scss': File not found (file:///c:/project/todo-list/src/styles/_utils.scss). 뜨면서 안되구요..
9장에서도 open-color 가 안되서 그냥 넘어갔는데 10장에서는 open-color가 필요하니..
어떻게 해야 하죠?

**Comment by velopert** [comment]
안녕하세요. 해당 프로젝트를 github 에 올려주시거나, 혹은 node_modules 를 제외하고 압축하여
구글드라이브 업로드 혹은 public.velopert@gmail.com 으로 메일 보내주시면 확인해드리겠습니다 :)

**Comment by weaklion** [comment]
확인해보니 @import 할때 파일 앞에 _를 붙여서 불러오는것 같네요.
다른 걸로 테스트 해보니 다른 파일에도 _가 붙여서 불러와서 문제가 생기는 것 같습니다.
vscode 사용중인데 vscode의 문제인가요?

**Comment by velopert** [comment]
앗 이메일 못받았는데 다시 보내주시겠어요?

**Comment by weaklion** [comment]
이메일이 안보내졌네요 ..
https://drive.google.com/open?id=1rAWyImwz-iW4EFY7upfcOzpltwLv8kq9
구글 드라이브 링크로 보냅니다 :)

**Comment by velopert** [comment]
음? 비밀번호가 있어요 :0

**Comment by weaklion** [comment]
아 깜빡했네요.. 비밀번호 123입니다 .ㅠ

**Comment by weaklion** [comment]
되는거 확인했습니다. 
뭐가 문제인지는 모르겠지만 새로  npx로  이전버전으로 다시 만들고 하니 되네요. 
감사합니다!

**Comment by velopert** [comment]
비밀번호 입력해도 압축이 이상하게 됐는지 풀리지 않는군요
무튼 해결이 됐다니 다행입니다.

일부 PC 에서는 npx 로만 이전버전이 제대로 설치되나보네요..!
