### ISSUE TITLE
p195 오탈자

### ISSUE THREAD

**Issue by weaklion** [velopert/learning-react#55]
src/styles/main.css => src/styles/main.scss
10.1.2.5 메인 스타일 설정에는 main.scss파일로 만들어라고 되어있네요.

**Comment by velopert** [comment]
https://github.com/velopert/learning-react/blob/master/corrections.md

쪽에 반영되어있습니다.

1쇄에서 오탈자가 꽤 있었습니다. 죄송합니다 :(
