### ISSUE TITLE
14장 todos.js 모듈 질문 드립니다

### ISSUE THREAD

**Issue by yeonhyung** [velopert/learning-react#58]
컨테이너에서는  ID를 넘겨주는데 
    handleRemove = (id) => {
        TodosActions.remove(id);
    } 
모듈에서는 이를 index 로 처리합니니다
    [REMOVE] : (state, action) =>  {
      const {index} = action.payload;
      return state.delete(index);
    }
예제는 다행히  ID 와 인덱스가 동일합니다만
실제로는 해당 ID에 맞는 인덱스를 state List에서 찾아서 처리해야 하겠지요
Map을 객체로 갖고 있는 List 에서 원하는 값이 있는 Map의 index를 찾는 방법을 좀 알려주세요

**Comment by velopert** [comment]
안녕하세요.

1쇄때 오류가 있었습니다.
https://github.com/velopert/learning-react/commit/a3ada1e5f96aba0c3e069d732952f4dcd0a5d1ad

이 부분 확인해주세요.

감사합니다!
