### ISSUE TITLE
15장 340페이지의  하단

### ISSUE THREAD

**Issue by sharpscar** [velopert/learning-react#60]
새 모듈을 만들었으니, 이 모듈의 리듀서를 루트 리듀서에도 넣어주세요.

src/index.js 가 아닌

src/modules/index.js 입니다.

아무생각없이 따라하다보니 헷갈리네요 ㅎㅎ

**Comment by velopert** [comment]
https://github.com/velopert/learning-react/blob/master/corrections.md

여기서 확인된 사항이라 close 합니다.

1쇄때 놓친것들이 꽤있었어요 ㅠㅠ 죄송합니다. 다른 오탈자들은 위 문서 확인해주세요~

즐거운 하루 되세요!
