### ISSUE TITLE
http://localhost:5000 에서 react-router 연습했던 프로젝트가 계속 뜹니다.

### ISSUE THREAD

**Issue by AreumAn0928** [velopert/learning-react#66]
안녕하세요.

현재 19장을 하고 있는데, 심심해서 http://localhost:5000을 쳐 보았는데 
전에 연습했던 프로젝트가 계속 떠 있어요.

서버를 띄우지도 않았고 컴퓨터도 재부팅 했는데 어떻게 떠 있는거죠?

![screen shot 2018-11-02 at 5 35 45 pm](https://user-images.githubusercontent.com/25269635/47941770-de0b3480-dec5-11e8-810d-35a7f06ec5dd.png)

**Comment by velopert** [comment]
Service Worker 가 등록됐기 때문입니다.
초기화하시려면 크롬 개발자도구의  Application -> Service Worker ->  Unregister 를 하시면 됩니다.
