### ISSUE TITLE
16장 질문입니다.

### ISSUE THREAD

**Issue by rnjsehgud84** [velopert/learning-react#68]
![p364](https://user-images.githubusercontent.com/43941269/48596895-54b43180-e99e-11e8-97ff-6e207127cedc.jpg)

16장 368페이지까지 코딩한 후 yarn start 한 후 입니다... 이유가 뭘까요...?

**Comment by velopert** [comment]
Router 가 아니라  Route 컴포넌트를 쓰셔야 합니다.
