### ISSUE TITLE
14장 redux-actions의 handleActions() 질문 드립니다.

### ISSUE THREAD

**Issue by polarmagpie** [velopert/learning-react#73]
305p에서는 액션에 따라 실행할 함수들을 가진 객체를 넣어 줄 때 키를 INCREMENT, DECREMENT로 넣어주줍니다.

그런데 310p의 todos.js에서 handleActions을 default로 export할 때는 키를 [INSERT], [TOGGLE] 같은 식으로 []로 키를 감쌉니다. 혹시나 해서 []를 지워보니 잘 작동하지 않고, 넣으면 작동해서 왜 이런 건지 이해가 잘 안 갑니다.

오래 고민하다가 도저히 답을 찾을 수 없어서 질문 남깁니다. 도움 주시면 정말 감사하겠습니다.

**Comment by SEOYOHAN** [comment]
안 보실 것 같지만... 그래도 혹시나 해서 남겨드립니다.
305p에서는 일반 문자열 값을 key로 'INCREMENT/DECREMENT'를 등록한 것이기 때문에 그대로 넣은 것이고,
310p에서는 위에서 정의한 문자열(todos/...)을 담은 변수를 넣은 키로 등록하는 것이기 때문에 문법적으로 대괄호로 감싸게 됩니당.

**Comment by polarmagpie** [comment]
스트링을 키로 쓰려면 []로 감싸줘야한다는 사실을 몰랐네요. 정말 감사합니다.
