### ISSUE TITLE
오탈자 14.1.3.3 Immutable 아이템수정

### ISSUE THREAD

**Issue by devjoo** [velopert/learning-react#74]
전자책이라 몇페이지 인지 정확히 기재를 못드려 죄송합니다. 

const newList = list.setIn([0, 'value'], list.getIn([0, 'value']) * 5);
에서 아래와 같이
list.setIn([0, 'value'], list.getIn([0, 'value'] * 5));
* 5 위치에 오타가 있습니다.

**Comment by velopert** [comment]
감사합니다 :)
