### ISSUE TITLE
[347p, 349p] store.js의 createStore() 파라미터 ReduxThunk 누락

### ISSUE THREAD

**Issue by SEOYOHAN** [velopert/learning-react#76]
한참 헤메다가 겨우 찾았습니다.. ㅎㅎ

서적 본문(347p)에는
"const store = createStore(modules, applyMiddleware(logger, pm));"
이런 식으로 기재되어 있어서 Thunk가 필요없는 줄 알았는데,

블로그에 올려놓으신 동일내용 포스팅을 보고
"const store = createStore(modules, applyMiddleware(logger, **ReduxThunk**, pm));"
로 고치니 정상 작동하는 군요! (349p 도 마찬가지 입니다.)

참고해주시기 바랍니다!

그리고 김민준님 항상 감사합니다.

**Comment by th-y** [comment]
**ReduxThunk** 사용 없이 아래와 같이 하면 정상적으로 작동합니다~

import { createStore, applyMiddleware } from 'redux';
import modules from './modules';

import { createLogger } from 'redux-logger';

// 사용하지 않으므로 주석 처리
// import ReduxThunk from 'redux-thunk';

import { createPromise } from 'redux-promise-middleware';

/*
    로그 미들웨어를 만들 때 설정을 커스터마이징할 수 있습니다.
    https://github.com/evgenyrodionov/redux-logger#options
*/

const logger = createLogger();
const promise = createPromise({
    promiseTypeSuffixes: ['PENDING', 'SUCCESS', 'FAILURE']
});

const store = createStore(modules, applyMiddleware(logger, promise));

export default store;

**Comment by th-y** [comment]
```
import { createStore, applyMiddleware } from 'redux';
import modules from './modules';

import { createLogger } from 'redux-logger';

// 사용하지 않으므로 주석 처리
// import ReduxThunk from 'redux-thunk';

import { createPromise } from 'redux-promise-middleware';

/*
    로그 미들웨어를 만들 때 설정을 커스터마이징할 수 있습니다.
    https://github.com/evgenyrodionov/redux-logger#options
*/

const logger = createLogger();
const promise = createPromise({
    promiseTypeSuffixes: ['PENDING', 'SUCCESS', 'FAILURE']
});

const store = createStore(modules, applyMiddleware(logger, promise));

export default store;
```

**ReduxTrunk** 없이도 작동 잘 되네요~

**Comment by th-y** [comment]
```
import { createStore, applyMiddleware } from 'redux';
import modules from './modules';

import { createLogger } from 'redux-logger';

// 사용하지 않으므로 주석 처리
// import ReduxThunk from 'redux-thunk';

import { createPromise } from 'redux-promise-middleware';

/*
    로그 미들웨어를 만들 때 설정을 커스터마이징할 수 있습니다.
    https://github.com/evgenyrodionov/redux-logger#options
*/

const logger = createLogger();
const promise = createPromise({
    promiseTypeSuffixes: ['PENDING', 'SUCCESS', 'FAILURE']
});

const store = createStore(modules, applyMiddleware(logger, promise));

export default store;
```

**ReduxTrunk** 없이 이렇게 하셔도 될 것 같아요.

**Comment by SEOYOHAN** [comment]
감사합니다.
