### ISSUE TITLE
10장 질문드립니다.

### ISSUE THREAD

**Issue by ddingjo** [velopert/learning-react#77]
10장 마지막 부분에 보면
TodoItem.js 파일 코드에서
</ div className={cx('delete')}  onClick={ (e) => { onRemove();  e.stopPropagation();}}>[지우기]</ div>

onClick 시에 직접 함수를 넣지 않고
todoItemHandleRemove 를  설정해서
</ div className={cx('delete')} onClick={ handleRemove }>[지우기]</ div> 
이렇게 해 볼려구 하는데 잘 되지가 않네요.;;
todoItemHandleRemove 에서 
onRemove 를 호출하고 
e.stopPropagation() 을 호출해도 될거같은데
어떻게 짜야 할지 도무지 감이 안잡이네요.ㅠㅠ
설명한번만 부탁드립니다.
태그 작성이 안되어서 /를 붙였습니다.

**Comment by SEOYOHAN** [comment]
e를 파라미터로 넣어 주면 동작할 거라고 보여집니다.

**Comment by velopert** [comment]
onRemove = (e) => {
   e.stopPropagation();
   /* ... */
}
