### ISSUE TITLE
22장(636p) 질문드립니다

### ISSUE THREAD

**Issue by rlawnsxo131** [velopert/learning-react#78]
코드스플리팅을 진행하는 내용중 webpack.config.pord.js의 ExtractTextPlugin의 옵션을 수정하는 부분을
진행하였는데 의문이 생겨 질문 드립니다.
현재 create-react-app v2가 릴리즈되고 해당 플러그인은 기본적인 옵션으로 설정이 되지 않는 현재
어느 부분을 수정해서 코드스플리팅시 CSS 파일이 코드스플리팅이 되지 않게 설정해야 하는지
몰라 질문 드립니다.

**Comment by velopert** [comment]
앗, 해당 부분은 제가 조만간 벨로그에 올릴 내용이긴한데
CRA v2 이상에서는 CSS 도 스플리팅되도록 작성하고
미리 불러오는 작업을 하는게 편합니다.

지금은 따로 작성한 튜토리얼이 없어서 코드 예제밖에 못드리겠네요..! 

https://github.com/vlpt-playground/react-ssr-sample
