### ISSUE TITLE
서적 오타관련 글 4

### ISSUE THREAD

**Issue by PEKKA4** [velopert/learning-react#8]
292페이지에
let object 2 ={
...
}

이부분에
...object
...object.d
...object.d.f
이부분
object 가아니라 object1 인것 같습니다

추가로 닫힌 이슈 중에서 #4 다시 확인해주세요. 맞다고는 하신것같은데 github 샘플 코드랑 비교해봐도 아닌것 같네요

**Comment by velopert** [comment]
확인 되었습니다. 감사합니다.
#4의 경우도 이전에 확인했었는데 까먹고 댓글을 안남겼었네요 ^^ 

추가적으로, 확인된 오탈자들은 따로 문서로 정리해서 레포에 올려놓도록하겠습니다.
