### ISSUE TITLE
5장 p113 / ValidationSample.js 예제 중

### ISSUE THREAD

**Issue by leoh7** [velopert/learning-react#80]
너무 사소한거라 말씀을 드려야 하나... 싶은데 ㅠㅠㅠ

handleChange 내부 setState() 뒤에는 세미콜론으로 닫혀있고
handleButtonClick 내부 setState() 뒤에는 세미콜론으로 안 닫혀 있는데....

매개변수를 받아다 쓰냐 안쓰냐에 따라 세미콜론을 적느냐 안 적느냐가 갈리는 것일까
하고 헛생각까지 하다가 ㅋㅋㅋㅋㅋㅋㅋㅋ 이슈를 달아봅니다!

책 너무 친절하게 잘 설명 되어 있어서 재밌게 공부하고 있어요! 감사합니다 ㅎㅎㅎ

**Comment by velopert** [comment]
앗... 사실 자바스크립트에서는 달은거나 안달으거나 큰 차이가 없습니다! 
저기에 없는건.. 그냥 제가 실수로 빠뜨린것같습니다 :) 큰신경쓰지않아도되요~
