### ISSUE TITLE
p73에서 p78까지 엉키는 느낌

### ISSUE THREAD

**Issue by andrewJYjang** [velopert/learning-react#81]
MyComponent 
string 아닌
숫자를 {  } 감싸는 설명을 하셨습니다.
그런데 이미 propsTypes 코딩으로 73페이지 내용의 맥을 끝은 지 한참 뒤에 설명하셔서
왠지 엉키는 느낌이 있네요.

**Comment by velopert** [comment]
죄송합니다, props 사용 -> prop types 설정해보기 -> 잘못된 props 전달 순서로되어있는데 어떤부분이 엉켜져있는건지 잘 이해가 가지 않네요 ^^ 

큰 이슈는 아닌것같아서 이슈는 닫아놓을게요!

감사합니다.
