### ISSUE TITLE
p123 App 컴포넌트 ScrollBox ref 버튼 내부 메서드 작성할 때 시스템 정지 문제

### ISSUE THREAD

**Issue by andrewJYjang** [velopert/learning-react#85]
p123 코드를 작성하면서 노트북 시스템 메모리 고갈 문제가 심각해집니다.
시스템을 재부팅해도,
해당 코드를 작성하면 갑자기 같은 문제가 생깁니다.
8G 메모리를 늘려야 하는 생각은 평소에 했었지만
혹시 내부 메서드 코드에 큰 문제가 있는 것은 아닐까요? 아니겠지죠!
저만 그런가요?

랜더링 문제가 이런 것인가요? 그리고 해당 코드는 책에 있는 것과 여기 github에 있는 것에 차이가 좀 있는데요. 가이드를 부탁드립니다.

**Comment by velopert** [comment]
현재 작성하신 ScrollBox.js 와 App.js 를 이슈쪽에 올려주시면 한번 확인해보겠습니다.
렉이 발생하지 않아야 정상입니다.
