### ISSUE TITLE
저의 시스템에서는 10장 p193부터 여기 깃허브 내용과 차이가 있어서요.

### ISSUE THREAD

**Issue by andrewJYjang** [velopert/learning-react#86]
저의 책은 9월15일 초판2쇄 발행으로 되어 있는데요. 2쇄라고 해서 최신 교정 내용이 전부 반영되지 않았나요? 생각했습니다. 

config 폴더 또는 registerServiceWorker.js 등이 책에서와 깃허브에 있는 데, CLI 작업으로 프로젝트를 만들 때에는 저의 시스템에 이렇게 책과 깃허브 내용과 다르거든요.

라이브러리 업데이트 때문인가요?
12월 19일 React v16.7.0에 대한 React Blog post가 있습니다만.

책 내용 품질에 있어서 9장, 10장부터 갑자기 큰 충격을 받게 됩니다.
이전까지는 코딩을 하나 하나 해보면서 정말 좋았거든요.

예를 들어서, p193 10.1.2.3 webpack 설정 파일 수정// 다음부터
css-loader 설정을 복사하여 ... 2줄은 리액트를 처음해보거나 frontend 기술을 익혀가는 사람에 입장에서 상당히 어려운 설명이 될 수 있다고 생각합니다.

**Comment by velopert** [comment]
앗, 불편을 드려서 죄송합니다. 책을 내놓고 얼마 안돼서 CRA 버전이 업데이트 되서요 ^^
책의 내용과 똑같이 진행하시려면, 

$ npx create-react-app sample-project --scripts-version=1.1.5

이렇게 프로젝트르 생성하셔야합니다~

**Comment by velopert** [comment]
자세한 사항은 https://github.com/velopert/learning-react#%EC%9D%BD%EC%96%B4%EC%A3%BC%EC%84%B8%EC%9A%94 를 참고해주세요.
