### ISSUE TITLE
맥북에서 리액트 설치도중 오류문의합니다

### ISSUE THREAD

**Issue by HANJANGWON** [velopert/learning-react#92]
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.0.5"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  /Users/han/node_modules/babel-loader (version: 7.1.5) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-loader" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /Users/han/node_modules/babel-loader is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-loader in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-loader.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

이러한오류가떠서 진행을 못하고있습니다 꼭 해결해주시길 부탁드리겠습니다ㅠㅠ

**Comment by hwj0623** [comment]
Create React App (CRA) 로 기본 탑재되는 node_module과 수동설치한 node_module의 버전 호환성 문제로 보입니다. (github에서 Vulability warining 띄워서 webpack 업그레이드 하다가 저도 겪어본 사항이라..) 
=> 우선 해당 CRA프로젝트 제거 후, Create React App (CRA) 로 프로젝트 설치시에 babel-loader가 설치되어 있는지 package.json파일이랑 해당 프로젝트의 node_modules에서 확인해주시고 별도 수동 설치 안하시는게 좋을 것 같습니다.
